name: create PlantUML Images
on: 
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generate SVG Diagrams

        with:
          args: -v -o images -tsvg plantuml
      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -o images -tpng plantuml
      - name: Archive created images
        uses: actions/upload-artifact@v3
        with:
          name: PlantUML images
          path: plantuml/images