name: create PlantUML JAR
on:
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
    # Auschecken der Sourcen
      - name: Checkout Source
        uses: actions/checkout@v2
    # Installieren von Java
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
    # Download von Plantuml als Jar mit Graphviz
      - name: Download plantuml file
        run: |
          wget -O plantuml.jar "https://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2022.5.jar" 
          ls -ltr
    # Generieren der Grafiken als SVG und PNG im Ordner images/diagrams
      - name: Generate Images
        run: |
          imagedir=images/diagrams
          mkdir -p $imagedir
          rm -rf images/diagrams/*
          java -version  
           for fullname in $(find src/plantuml/ -type f -name '*.puml')
          do
            echo "Fullname: ${fullname}"
            base=$(basename "${fullname}" .puml)
            echo "Basename: ${base}"
            outdir=$(dirname $fullname | sed s+src/plantuml+${imagedir}+)
            echo "Outdir: ${outdir}"
            mkdir -p $outdir
            plantoutdir="${PWD}/${outdir}"
            # -v für verbose Output (Debugging)
            # -checkmetadata prüft anhand der Metadaten, 
            # ob aus diesen bereits das passende png/svg erzeugt worden ist
            # -o setzt den Ordner in dem die png/svg Dateien abgelegt werden
            plantargs="-v -checkmetadata -o ${plantoutdir} ${fullname}"
            echo "PlantOutdir: ${plantoutdir}"
            tree ./
            # Seperate Aufrufe sind notwendig, 
            # da nicht beide Ausgabetypen in einem Aufruf übergeben werden können
            java -jar plantuml.jar -tpng ${plantargs} 
            java -jar plantuml.jar -tsvg ${plantargs}
          done
          ls -al 
          tree ./
      # Upload der Bilder als Artefakt für Debugging
      - name: Archive created images
        uses: actions/upload-artifact@v3
        with:
          name: PlantUML images
          path: images/diagrams/
      # Commit der neu erzeugten Bilder
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8
        with:
          add: 'images/diagrams/'

