name: create PlantUML Images with Action
on: 
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
    # Auschecken der Sourcen
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generated Structure
        run: |
          tree
    # Generieren der svg Diagramme in einem images Ordner, 
    # der unterhalb der Ordner angelegt wird, in dem die PlantUML-Dateien gefunden werden
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -o images -tsvg src/plantuml
    # Generieren der png Diagramme in einem images Ordner, 
    # der unterhalb der Ordner angelegt wird, in dem die PlantUML-Dateien gefunden werden
      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -o images -tpng src/plantuml
    # Ausgabe der Ordnerstruktur für Debugging
      - name: Generated Structure
        run: |
          tree
    # Upload der Artefakte an den Workflow für Debugging
      - name: Archive created images
        uses: actions/upload-artifact@v3
        with:
          name: PlantUML images
          path: plantuml/
