name: create PlantUML Images
on: 
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
      - run: echo ${{ steps.last_successful_commit.outputs.commit_hash }}
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -o images -tsvg plantuml
      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -o images -tpng plantuml
      - name: Generated Structure
        run: |
          tree ./
      - name: Archive created images
        uses: actions/upload-artifact@v3
        with:
          name: PlantUML images
          path: plantuml/
