# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diagrams:
    name: Draw diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: create directories
        run: |
          imagedir=images/diagrams
          mkdir -p $imagedir
      - name: create images
        uses: cloudbees/plantuml-github-action@master
        with:
          args: '-v -o images/diagrams -tpng /home/runner/work/plantuml/plantuml/'
      - name: debugger
        run: |
          pwd
          ls -la
          ls -la images/diagrams
      
