# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diagrams:
    name: Draw diagrams
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          git diff-tree -r --no-commit-id --summary ${{ github.sha }} \
          | awk -F' ' '{
            # ensure we are not trying to process deleted files
            # only process puml files
            # do not try to process our theme or custom config
            if ( $1 !~ /^delete$/ && $4 ~ /\.puml$/ && $4 !~ /(theme|config)\.puml$/ )
            {
              # only print the file name and strip newlines for spaces
              printf "::set-output name=files::" "%s ", $4
            }
          }
          END { print "" } # ensure we do print a newline at the end
          '
      - name: create directories
        run: |
          imagedir=images/diagrams
          mkdir -p $imagedir
      - name: create images
        uses: cloudbees/plantuml-github-action@master
        with:
          args: '-v -o images/diagrams -tpng test2.puml'
      - name: debugger
        run: |
          pwd
          ls -la
          ls -la images/diagrams
      
