name: create PlantUML JAR
on:
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Generate Images
        run: |
          mkdir -p images/diagrams
          rm -rf images/diagrams/*
          java -version
          wget https://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2022.5.jar/download
          for fullname in src/plantuml/*.puml
          do
            base=$(basename -- "$fullname")
            echo ${base%.*}
            java -jar plantuml.jar -o images/diagrams/ -tpng src/plantuml/${base%.*}.puml
          done

