name: create PlantUML JAR
on:
  workflow_dispatch:
jobs:
  diagrams:
    name: Create PlantUML images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Download plantuml file
        run: |
          wget -O plantuml.jar "https://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2022.5.jar" 
          ls -ltr
      - name: Generate Images
        run: |
          imagedir=images/diagrams
          mkdir -p $imagedir
          rm -rf images/diagrams/*
          java -version  
           for fullname in $(find src/plantuml/ -type f -name '*.puml')
          do
            echo "Fullname: ${fullname}"
            base=$(basename "${fullname}" .puml)
            echo "Basename: ${base}"
            outdir=$(dirname $fullname | sed s+src/plantuml+${imagedir}+)
            #outdir=$($PWD/$outdir)
            echo "Outdir: ${outdir}"
            mkdir -p $outdir
            tree ./
            java -jar plantuml.jar -v -o ${outdir} -tpng ${fullname}
            java -jar plantuml.jar -v -o ${outdir} -tsvg ${fullname}
          done
          ls -al 
          tree ./
      - name: Archive created images
        uses: actions/upload-artifact@v3
        with:
          name: PlantUML images
          path: images/diagrams/*

